language: python

python:
  - 2.7

sudo: false

env:
  global:
    - secure: "fumoc9CFl8Nypi9iMRuJAkDv4gHptcikEFlkiPOUz6wBiCyKj+w7Hl917wMOLqKuNGM0gT4suFG06quLI6hDTUhmWwulsWNXpRaql5ukhvCFMyqIx+kkuQGYe1aKcRmeDZqYsc3KEvSb2MOoeLIvsfqxjj3mvZwgaN4zaUthnZM="

script:
  - set -e

  - pip install -r requirements.txt
  - pip install sphinx numpydoc sphinx_gallery
  - python setup.py build_ext --inplace

  - cd docs
  - make html
  - cd ..
  
  - virtualenv venv --python=python3.5
  - source venv/bin/activate
  - pip install git+https://github.com/r-b-g-b/doctr.git@deploy-to-any-branch  
  - doctr deploy --deploy-repo gallantlab/gallantlab.github.io --deploy-branch-name master --gh-pages-docs / --no-require-master
  - deactivate