language: python

python:
  - 3.5

sudo: false

env:
  global:
    - secure: "fumoc9CFl8Nypi9iMRuJAkDv4gHptcikEFlkiPOUz6wBiCyKj+w7Hl917wMOLqKuNGM0gT4suFG06quLI6hDTUhmWwulsWNXpRaql5ukhvCFMyqIx+kkuQGYe1aKcRmeDZqYsc3KEvSb2MOoeLIvsfqxjj3mvZwgaN4zaUthnZM="

script:
  - set -e
  - # Command to build your docs
  - pip install -r requirements.txt
  - pip install sphinx numpydoc sphinx_gallery
  - pip install git+https://github.com/r-b-g-b/doctr.git@deploy-to-any-branch
  - python setup.py build_ext --inplace
  - cd docs
  - make html
  - cd ..
  - doctr deploy --deploy-repo gallantlab/gallantlab.github.io --deploy-branch-name master --gh-pages-docs / --no-require-master
