language: python
python:
  - 3.5

sudo: false
env:
  global:
    secure: "<your secure key from doctr here>"

script:
  - set -e
  - # Command to build your docs
  - pip install -r requirements.txt
  - pip install sphinx doctr numpydoc sphinx_gallery
  - python setup.py build_ext --inplace
  - cd docs
  - make html
  - cd ..
  - doctr deploy --deploy-repo gallantlab/gallantlab.github.io --no-require-master
